name: Update Zen Browser Version

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release
        id: get_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/zen-browser/desktop/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - name: Extract version
        id: extract_version
        run: |
          cat << 'EOF' | grep -o '"tag_name": "[^"]*"' | sed 's/"tag_name": "\(.*\)"/\1/' > version.txt
          ${{ steps.get_release.outputs.data }}
          EOF
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Update flake.nix
        run: |
          sed -i 's/version = "[^"]*"/version = "${{ steps.extract_version.outputs.VERSION }}"/' flake.nix
          # Update the hash specific.sha256
          specific=$(nix-prefetch-url --type sha256 --unpack https://github.com/zen-browser/desktop/releases/download/${{ steps.extract_version.outputs.VERSION }}/zen.linux-x86_64.tar.xz)
          sed -i '/specific/,/sha256/s/sha256 = "sha256:[^"]*"/sha256 = "sha256:'$specific'"/' flake.nix
          echo $specific
          # Update the hash generic.sha256
          generic=$(nix-prefetch-url --type sha256 --unpack https://github.com/zen-browser/desktop/releases/download/${{ steps.extract_version.outputs.VERSION }}/zen.linux-x86_64.tar.xz)
          echo $generic
          sed -i '/generic/,/sha256/s/sha256 = "sha256:[^"]*"/sha256 = "sha256:'$generic'"/' flake.nix
          cat flake.nix
          nix flake update
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add flake.nix
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: bump Zen Browser to ${{ steps.extract_version.outputs.VERSION }}" && git push)
